### ISSUE TITLE
Actualizar entidad de "Producto"

### ISSUE THREAD

**Issue by JackmoonGit** [1774-ProyectoIntegrador/backend#15]
Para enriquecer la información que maneja nuestra API sobre productos, es necesario expandir la entidad Producto con campos adicionales que permitan capturar detalles más específicos y relevantes sobre los productos. Se propone mantener los campos básicos actuales (nombre, descripción, etc.) y agregar la posibilidad de vincular una nueva entidad "ProductDetails" que permita asignar o modificar detalles adicionales de forma flexible.

**Tareas**

- [x] -  Actualizar la entidad Producto para incluir nuevos campos: Marca, Modelo, Categoría, Precio, Stock.
- [x] -  Crear una nueva entidad "ProductDetails" que pueda almacenar información adicional como: Tamaño del producto, Tipo de montura, Formato de video, Megapíxeles, etc.
- [x] -  Establecer una relación opcional entre Producto y ProductDetails para que los detalles puedan ser añadidos o actualizados independientemente.
- [ ] -  Actualizar el formulario de ingreso de productos para reflejar estos cambios, asegurando que los campos básicos sean ingresados al crear un producto y permitiendo la opción de añadir detalles adicionales posteriormente.
- [ ] -  Implementar validaciones adecuadas en el backend para los nuevos campos, asegurando la integridad de los datos.

**Consideraciones técnicas**

- Modificar las clases de entidad en el backend de Spring Boot.
- Ajustar los DTOs y los mapeadores para soportar la transferencia de los nuevos datos.
- Actualizar la base de datos con las nuevas estructuras de datos necesarias.
- Implementar la lógica de negocio para manejar la creación y actualización de los detalles del producto de manera opcional.

**Beneficios esperados**

- Flexibilidad: Mayor flexibilidad en el manejo de la información del producto, permitiendo una descripción más completa y ajustada a las necesidades del mercado.
- Escalabilidad: Facilidad para añadir o modificar detalles del producto sin afectar la estructura principal.
- Mejor experiencia de usuario: Al proporcionar información más detallada y relevante sobre los productos en la plataforma.

https://www.figma.com/file/jSTzXj7hHAN1hdhn7vvlBd/ProyectoIntregadorDH?type=design&node-id=110-368&mode=design&t=UkBjNfpDF7bBKMT6-4

**Comment by JackmoonGit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#15 - Actualización de la entidad Producto](https://trello.com/c/lAkOoOkU/11-15-actualizaci%C3%B3n-de-la-entidad-producto)

**Comment by MatiasCastellon1214** [comment]
Actualización de la entidad Producto: Realizado.

Creación de la entidad ProductDetail: Realizado. Detalle: Sólo se crearon algunos atributos para verificar la relación entre las entidades Product y ProductDetail.

Establecer relación opcional entre las entidades Product y ProductDetail: Realizado.
Tarea pendiente: Hacer el Pull Request correspondiente.

**Comment by JackmoonGit** [comment]
@MatiasCastellon1214 sube la Pull Request al repositorio para su validación.

Saludos!

**Comment by MatiasCastellon1214** [comment]
Se realizó el PullRequest correspondiente a la actualización de la entidad Producto, creación de la entidad ProductDetail, establecer relación opcional entre ambas entidades.
