### ISSUE TITLE
Actualizar función: "Registrar producto"

### ISSUE THREAD

**Issue by JackmoonGit** [1774-ProyectoIntegrador/backend#25]
## Historia de Usuario

**Como** administrador,
**quiero** poder agregar nuevos productos,
**para** mantener actualizado el catálogo de productos disponibles.

---

## Descripción

Esta tarea permite al administrador agregar nuevos productos al catálogo del sitio. Incluye la implementación de la lógica de backend necesaria para gestionar la creación y almacenamiento de productos, así como la validación de datos y manejo de imágenes.

## Criterios de Aceptación

- [x] La API de backend debe proporcionar un endpoint para agregar productos.
- [x] La API debe aceptar campos como nombre, descripción e imagen del producto.
- [ ] Se debe poder subir una o más imágenes del producto.
- [x] El producto debe guardarse correctamente en la base de datos.
- [x] Si se intenta agregar un producto con un nombre que ya existe, la API debe devolver un mensaje de error indicando que el nombre ya está en uso.

## Definición de Hecho (DoD)

- [ ] Código revisado
- [ ] Pruebas unitarias pasadas
- [ ] Pruebas de integración pasadas
- [ ] Documentación de la API actualizada
- [ ] Desplegado en el entorno de prueba

## Tareas

- [x] Crear el endpoint `POST /productos` para agregar un nuevo producto.
- [x] Implementar la lógica de negocio para manejar la creación de productos.
- [ ] Validar que el nombre del producto no esté duplicado en la base de datos.
- [ ] Implementar la funcionalidad para cargar y almacenar imágenes del producto.
- [x] Guardar los detalles del producto en la base de datos.
- [ ] Escribir las pruebas unitarias para el endpoint `POST /productos`.
- [ ] Escribir las pruebas de integración para el flujo completo de agregar un producto.

## Prioridad

Alta

---

### Información Adicional

Utilizamos Spring Boot para el backend. Asegúrate de seguir las mejores prácticas para la creación de endpoints RESTful y la gestión de errores.

**Comment by aldrinj0se** [comment]
Voy a trabajar en la tarea de poder subir una o varias imagenes al registrar un producto
