### ISSUE TITLE
Listar productos

### ISSUE THREAD

**Issue by JackmoonGit** [1774-ProyectoIntegrador/backend#26]
## Historia de Usuario: Listar productos

**Como** administrador,
**quiero** poder visualizar una lista de productos disponibles,
**para** poder gestionarlos con facilidad.

---

## Descripción

Esta tarea permite al administrador visualizar una lista de todos los productos disponibles en el sitio dentro del panel de administración. La lista debe incluir columnas para "Id", "Nombre" y "Acciones".

## Criterios de Aceptación

- [x] La API de backend debe proporcionar un endpoint para listar productos.
- [x] La API debe devolver todos los productos disponibles con sus detalles.
- [x] Los productos devueltos deben incluir "Id", "Nombre" y los datos necesarios para las acciones.
- [ ] Se deben mostrar como máximo 10 productos aleatorios.

## Definición de Hecho (DoD)

- [ ] Código revisado
- [ ] Pruebas unitarias pasadas
- [ ] Pruebas de integración pasadas
- [ ] Documentación de la API actualizada
- [ ] Desplegado en el entorno de prueba

## Tareas

- [x] Crear el endpoint `GET /productos` para listar todos los productos disponibles.
- [x] Implementar la lógica para obtener los productos de la base de datos.
- [x] Asegurar que los productos devueltos incluyan "Id", "Nombre" y los datos necesarios para las acciones.
- [ ] Escribir las pruebas unitarias para el endpoint `GET /productos`.
- [ ] Escribir las pruebas de integración para el flujo completo de listar productos.
- [ ] Implementar la lógica para limitar 10 productos, con paginación y si se mostrarán de forma aletoria utilizando booleanos. El endpoint debería ser: `GET /productos/?page=0&limit=10&random=true`

## Prioridad

Alta

---

### Información Adicional

Utilizamos Spring Boot para el backend. Asegúrate de seguir las mejores prácticas para la creación de endpoints RESTful y la gestión de errores.

**Comment by MatiasCastellon1214** [comment]
Trabajando en criterios de aceptación

**Comment by JackmoonGit** [comment]
- Falta implementación de paginación
`Implementar la lógica para limitar 10 productos, con paginación y si se mostrarán de forma aletoria utilizando booleanos. El endpoint debería ser: GET /productos/?page=0&limit=10&random=true`
